### ISSUE TITLE
Time based definition of trial/block duration

### ISSUE THREAD

**Issue by PhilippWanner** [ssciwr/vstt#152]
Adding an option that allows to define trial/block duration via time:
- At the moment, there is only the option to set the number of “repetitions” to define the duration of a trial/block (e.g. 5 repetitions of a sequence of 8 targets). An additional option that allows to enter time in seconds to define trial/block duration would be great (e.g. repeat a sequence of 8 targets as often as possible in 30 secs)

**Comment by lkeegan** [comment]
(4th priority)
Could implement as a max time for a trial/block (which by default is infinite)
Partially completed trial should be stopped and not included in results
