### ISSUE TITLE
add polygon area statistic to GUI

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/vstt#200]
To follow on from #182 this functionality can now also be integrated into the main program:

### Statistics

- add an `_area(mouse_positions: np.ndarray) -> float: ` or similar function to stat.py
  - calculates the area from the mouse positions as is already done in the example notebook
  - for comparison here is a simple function that just calculates the distance: https://github.com/ssciwr/vstt/blob/c397a81f59041db8f3a93cb86820672a709e3106/src/vstt/stat.py#L259-L263
- add tests of the above `_area` function to tests/test_stat.py
  - for comparison here are the tests for `_distance`: https://github.com/ssciwr/vstt/blob/c397a81f59041db8f3a93cb86820672a709e3106/tests/test_stat.py#L47-L65
- add the calculated area data to the stats dataframe
  - https://github.com/ssciwr/vstt/blob/c397a81f59041db8f3a93cb86820672a709e3106/src/vstt/stat.py#L103

### Visualization

- add `areas` or similar to the display options (with default value `False`)
  - https://github.com/ssciwr/vstt/blob/c397a81f59041db8f3a93cb86820672a709e3106/src/vstt/display.py#L8
- add the area to the displayed statistics texts
  - https://github.com/ssciwr/vstt/blob/c397a81f59041db8f3a93cb86820672a709e3106/src/vstt/vis.py#L145
- display the filled area instead of just the paths in vis.py
  - suggestion: maybe we can just combine `row.to_center_mouse_positions` `row.to_target_mouse_positions` and add
    - `fillColor=colors[row.target_index]`
    - `closeShape=True`
  - https://github.com/ssciwr/vstt/blob/c397a81f59041db8f3a93cb86820672a709e3106/src/vstt/vis.py#L251-L277

**Comment by ZoeJacky** [comment]
resolved by #241
